.TH TEXTPAD-EDITOR "1" "User Commands"

.SH NAME
Textpad Editor -  Simple and lightweight text editor

.SH DESCRIPTION
Textpad Editor is a simple, general-purpose, cross-platform text editor written using the Qt toolkit. Textpad aims to be faster and more lightweight than most text editors, but as useful as them. 
Additionally, Textpad supports syntax highlighting, word count, line count and comes with 5 different color schemes.
.PP
.B Textpad
has no command line options. Please run it under X.

.SH SYNOPSIS
.B textpad-editor [FILE]

.SH OPTIONS
.B textpad-editor
has no options.

.SH "SEE ALSO"
Homepage: http://textpad-editor.sf.net/

.SH AUTHOR
This manual page was written by Alex S. <alex_sr97@outlook.com> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
